FROM mcr.microsoft.com/azure-functions/python:4-python3.10-core-tools
# RUN mkdir -p mongo_crypt_shared
# RUN curl -OL https://downloads.mongodb.com/linux/mongo_crypt_shared_v1-linux-x86_64-enterprise-ubuntu2004-7.0.2.tgz 
# RUN tar -zxvf mongo_crypt_shared_v1-linux-x86_64-enterprise-ubuntu2004-7.0.2.tgz -C mongo_crypt_shared